name: Quality

on: [push, pull_request] 

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r qa-requirements.txt

    - name: Test
      run: |
        bash -ex qa/test.sh

